### ISSUE TITLE
Needs License

### ISSUE THREAD

**Issue by Symbolics** [fiddlerwoaroof/cl-git#1]
Great stuff. I was about to embark on exactly the same project; glad I decided to look around first. The repo could use a license file (and _please_ make this BSD/MIT/Boost/etc).

Also wondering if you considered a with-repository ... macro rather than in-repository ... function? That's the route I was leaning; it might make it easier when dealing with multiple repositories.

**Comment by fiddlerwoaroof** [comment]
Thanks, I'll push a license: my general policy is MIT for libraries, GPL of some sort for applications: so this'll be MIT.

I agree about the with-repository macro: I'll push that up too.

**Comment by fiddlerwoaroof** [comment]
I've pushed the license.  I've been thinking about the public interface of this library recently: if you have any thoughts about how this should work, I'd be interested in a proposal.

**Comment by Symbolics** [comment]
Not too many thoughts, other than it would be nice to be able to do something like this:
(with-repository <URL | Directory | Name> :branch "master" 
    (do-something ... ))
I'd probably start with the most common operations in a workflow. Push, fetch, merge, clone, diff, etc. You may already know this, but there is a porcelain called Magit for emacs that might serve as inspiration. Each operation is a separate file, which make sense and allows for easy extensions.

    On Sunday, July 21, 2019, 11:38:17 AM GMT+8, Ed Langley <notifications@github.com> wrote:  
 
 
I've pushed the license. I've been thinking about the public interface of this library recently: if you have any thoughts about how this should work, I'd be interested in a proposal.
